[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_song_nft = "4L1UMoj8j4UNEYetmGBj1SQaS1cvzuEzSbKrCvVDVKnK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/namblard/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
